# Generated by Django 5.0.6 on 2024-06-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='joined_date',
            new_name='date_joined',
        ),
    ]
